global_frame: odom
track_unknown_space: true

plugins:
  - {name: obstacle_layer,                 type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}
