# Robot footprint
#footprint: [[-0.5, -0.33], [-0.5, 0.33], [0.5, 0.33], [0.5, -0.33]]
robot_radius: 0.4

# Distance between footprint and obstacles
footprint_padding: 0.05

robot_base_frame: base_link

update_frequency: 5.0
publish_frequency: 5.0
transform_tolerance: 2
resolution: 0.02

# Distance in which something becomes an obstacle
obstacle_range: 4.0
raytrace_range: 3.0

#Publish full costmap
always_send_full_costmap: true 

controller_patience: 2.0

NavfnROS:
    allow_unknown: true

# Make the costmap be centered on the robot position
rolling_window: true

#layer definitions
obstacle_layer:
  min_obstacle_height: -10.0
  max_obstacle_height: 50.0
  observation_sources: point_cloud_sensor
  point_cloud_sensor: 
    sensor_frame: camera_link
    data_type: PointCloud2
    topic: camera/depth/points
    marking: true
    clearing: true
    min_obstacle_height: -10.0
    max_obstacle_height: 50.0

# Safe distance from obstacles
inflation:
    inflation_radius: 0.3

recovery_behaviors:
  - name: 'conservative_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'aggressive_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'rotate_recovery'
    type: 'rotate_recovery/RotateRecovery'

conservative_reset:
  reset_distance: 0.3
  layer_names: ['obstacle_layer']

aggressive_reset:
  reset_distance: 0.1
  layer_names: ['obstacles_layer']

