# Robot footprint
footprint: [[-0.35, -0.3], [-0.35, 0.3], [0.35, 0.3], [0.35, -0.3]]
#robot_radius: 0.4

# Distance between footprint and obstacles
footprint_padding: 0.01

robot_base_frame: base_link

update_frequency: 10.0
publish_frequency: 3.0

publish_cost_grid_pc: true

transform_tolerance: 2
resolution: 0.02

# Distance in which something becomes an obstacle
obstacle_range: 2.5
raytrace_range: 3.0

#Publish full costmap
always_send_full_costmap: true

planner_patience: 5.0
#controller_patience: 2.0

#layer definitions
static:
    map_topic: map
    subscribe_to_updates: true

obstacles_layer:
  min_obstacle_height: -10.0
  max_obstacle_height: 50.0
  observation_sources: point_cloud_sensor
  point_cloud_sensor: 
    sensor_frame: camera_link
    data_type: PointCloud2
    topic: camera/depth/points
    marking: true
    clearing: true
    min_obstacle_height: -10.0
    max_obstacle_height: 50.0

inflation:
    inflation_radius: 1.0
    cost_scaling_factor: 1.0

recovery_behaviors:
  - name: 'conservative_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'rotate_recovery'
    type: 'rotate_recovery/RotateRecovery'
  - name: 'aggressive_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'

conservative_reset:
  reset_distance: 1.0

aggressive_reset:
  reset_distance: 0.0

